/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Solver;

/**
 *
 * @author Tech
 */
public class Input extends javax.swing.JPanel {

    /**
     * Creates new form Input
     */
    public Input() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        j00 = new javax.swing.JTextField();
        j10 = new javax.swing.JTextField();
        j20 = new javax.swing.JTextField();
        j30 = new javax.swing.JTextField();
        j40 = new javax.swing.JTextField();
        j50 = new javax.swing.JTextField();
        j60 = new javax.swing.JTextField();
        j70 = new javax.swing.JTextField();
        j80 = new javax.swing.JTextField();
        j01 = new javax.swing.JTextField();
        j11 = new javax.swing.JTextField();
        j21 = new javax.swing.JTextField();
        j31 = new javax.swing.JTextField();
        j41 = new javax.swing.JTextField();
        j51 = new javax.swing.JTextField();
        j61 = new javax.swing.JTextField();
        j71 = new javax.swing.JTextField();
        j81 = new javax.swing.JTextField();
        j02 = new javax.swing.JTextField();
        j12 = new javax.swing.JTextField();
        j22 = new javax.swing.JTextField();
        j32 = new javax.swing.JTextField();
        j42 = new javax.swing.JTextField();
        j52 = new javax.swing.JTextField();
        j62 = new javax.swing.JTextField();
        j72 = new javax.swing.JTextField();
        j82 = new javax.swing.JTextField();
        j03 = new javax.swing.JTextField();
        j13 = new javax.swing.JTextField();
        j23 = new javax.swing.JTextField();
        j33 = new javax.swing.JTextField();
        j43 = new javax.swing.JTextField();
        j53 = new javax.swing.JTextField();
        j63 = new javax.swing.JTextField();
        j73 = new javax.swing.JTextField();
        j83 = new javax.swing.JTextField();
        j04 = new javax.swing.JTextField();
        j14 = new javax.swing.JTextField();
        j24 = new javax.swing.JTextField();
        j34 = new javax.swing.JTextField();
        j44 = new javax.swing.JTextField();
        j54 = new javax.swing.JTextField();
        j64 = new javax.swing.JTextField();
        j74 = new javax.swing.JTextField();
        j84 = new javax.swing.JTextField();
        j05 = new javax.swing.JTextField();
        j15 = new javax.swing.JTextField();
        j25 = new javax.swing.JTextField();
        j35 = new javax.swing.JTextField();
        j45 = new javax.swing.JTextField();
        j55 = new javax.swing.JTextField();
        j65 = new javax.swing.JTextField();
        j75 = new javax.swing.JTextField();
        j85 = new javax.swing.JTextField();
        j06 = new javax.swing.JTextField();
        j16 = new javax.swing.JTextField();
        j26 = new javax.swing.JTextField();
        j36 = new javax.swing.JTextField();
        j46 = new javax.swing.JTextField();
        j56 = new javax.swing.JTextField();
        j66 = new javax.swing.JTextField();
        j76 = new javax.swing.JTextField();
        j86 = new javax.swing.JTextField();
        j07 = new javax.swing.JTextField();
        j17 = new javax.swing.JTextField();
        j27 = new javax.swing.JTextField();
        j37 = new javax.swing.JTextField();
        j47 = new javax.swing.JTextField();
        j57 = new javax.swing.JTextField();
        j67 = new javax.swing.JTextField();
        j77 = new javax.swing.JTextField();
        j87 = new javax.swing.JTextField();
        j08 = new javax.swing.JTextField();
        j18 = new javax.swing.JTextField();
        j28 = new javax.swing.JTextField();
        j38 = new javax.swing.JTextField();
        j48 = new javax.swing.JTextField();
        j58 = new javax.swing.JTextField();
        j68 = new javax.swing.JTextField();
        j78 = new javax.swing.JTextField();
        j88 = new javax.swing.JTextField();

        j00.setMinimumSize(new java.awt.Dimension(6, 6));
        j00.setPreferredSize(new java.awt.Dimension(25, 25));
        j00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j00ActionPerformed(evt);
            }
        });

        j10.setMinimumSize(new java.awt.Dimension(6, 6));
        j10.setPreferredSize(new java.awt.Dimension(25, 25));
        j10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j10ActionPerformed(evt);
            }
        });

        j20.setMinimumSize(new java.awt.Dimension(6, 6));
        j20.setPreferredSize(new java.awt.Dimension(25, 25));
        j20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j20ActionPerformed(evt);
            }
        });

        j30.setMinimumSize(new java.awt.Dimension(6, 6));
        j30.setPreferredSize(new java.awt.Dimension(25, 25));
        j30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j30ActionPerformed(evt);
            }
        });

        j40.setMinimumSize(new java.awt.Dimension(6, 6));
        j40.setPreferredSize(new java.awt.Dimension(25, 25));
        j40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j40ActionPerformed(evt);
            }
        });

        j50.setMinimumSize(new java.awt.Dimension(6, 6));
        j50.setPreferredSize(new java.awt.Dimension(25, 25));
        j50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j50ActionPerformed(evt);
            }
        });

        j60.setMinimumSize(new java.awt.Dimension(6, 6));
        j60.setPreferredSize(new java.awt.Dimension(25, 25));
        j60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j60ActionPerformed(evt);
            }
        });

        j70.setMinimumSize(new java.awt.Dimension(6, 6));
        j70.setPreferredSize(new java.awt.Dimension(25, 25));
        j70.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j70ActionPerformed(evt);
            }
        });

        j80.setMinimumSize(new java.awt.Dimension(6, 6));
        j80.setPreferredSize(new java.awt.Dimension(25, 25));
        j80.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j80ActionPerformed(evt);
            }
        });

        j01.setMinimumSize(new java.awt.Dimension(6, 6));
        j01.setPreferredSize(new java.awt.Dimension(25, 25));
        j01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j01ActionPerformed(evt);
            }
        });

        j11.setMinimumSize(new java.awt.Dimension(6, 6));
        j11.setPreferredSize(new java.awt.Dimension(25, 25));
        j11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j11ActionPerformed(evt);
            }
        });

        j21.setMinimumSize(new java.awt.Dimension(6, 6));
        j21.setPreferredSize(new java.awt.Dimension(25, 25));
        j21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j21ActionPerformed(evt);
            }
        });

        j31.setMinimumSize(new java.awt.Dimension(6, 6));
        j31.setPreferredSize(new java.awt.Dimension(25, 25));
        j31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j31ActionPerformed(evt);
            }
        });

        j41.setMinimumSize(new java.awt.Dimension(6, 6));
        j41.setPreferredSize(new java.awt.Dimension(25, 25));
        j41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j41ActionPerformed(evt);
            }
        });

        j51.setMinimumSize(new java.awt.Dimension(6, 6));
        j51.setPreferredSize(new java.awt.Dimension(25, 25));
        j51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j51ActionPerformed(evt);
            }
        });

        j61.setMinimumSize(new java.awt.Dimension(6, 6));
        j61.setPreferredSize(new java.awt.Dimension(25, 25));
        j61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j61ActionPerformed(evt);
            }
        });

        j71.setMinimumSize(new java.awt.Dimension(6, 6));
        j71.setPreferredSize(new java.awt.Dimension(25, 25));
        j71.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j71ActionPerformed(evt);
            }
        });

        j81.setMinimumSize(new java.awt.Dimension(6, 6));
        j81.setPreferredSize(new java.awt.Dimension(25, 25));
        j81.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j81ActionPerformed(evt);
            }
        });

        j02.setMinimumSize(new java.awt.Dimension(6, 6));
        j02.setPreferredSize(new java.awt.Dimension(25, 25));
        j02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j02ActionPerformed(evt);
            }
        });

        j12.setMinimumSize(new java.awt.Dimension(6, 6));
        j12.setPreferredSize(new java.awt.Dimension(25, 25));
        j12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j12ActionPerformed(evt);
            }
        });

        j22.setMinimumSize(new java.awt.Dimension(6, 6));
        j22.setPreferredSize(new java.awt.Dimension(25, 25));
        j22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j22ActionPerformed(evt);
            }
        });

        j32.setMinimumSize(new java.awt.Dimension(6, 6));
        j32.setPreferredSize(new java.awt.Dimension(25, 25));
        j32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j32ActionPerformed(evt);
            }
        });

        j42.setMinimumSize(new java.awt.Dimension(6, 6));
        j42.setPreferredSize(new java.awt.Dimension(25, 25));
        j42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j42ActionPerformed(evt);
            }
        });

        j52.setMinimumSize(new java.awt.Dimension(6, 6));
        j52.setPreferredSize(new java.awt.Dimension(25, 25));
        j52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j52ActionPerformed(evt);
            }
        });

        j62.setMinimumSize(new java.awt.Dimension(6, 6));
        j62.setPreferredSize(new java.awt.Dimension(25, 25));
        j62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j62ActionPerformed(evt);
            }
        });

        j72.setMinimumSize(new java.awt.Dimension(6, 6));
        j72.setPreferredSize(new java.awt.Dimension(25, 25));
        j72.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j72ActionPerformed(evt);
            }
        });

        j82.setMinimumSize(new java.awt.Dimension(6, 6));
        j82.setPreferredSize(new java.awt.Dimension(25, 25));
        j82.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j82ActionPerformed(evt);
            }
        });

        j03.setMinimumSize(new java.awt.Dimension(6, 6));
        j03.setPreferredSize(new java.awt.Dimension(25, 25));
        j03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j03ActionPerformed(evt);
            }
        });

        j13.setMinimumSize(new java.awt.Dimension(6, 6));
        j13.setPreferredSize(new java.awt.Dimension(25, 25));
        j13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j13ActionPerformed(evt);
            }
        });

        j23.setMinimumSize(new java.awt.Dimension(6, 6));
        j23.setPreferredSize(new java.awt.Dimension(25, 25));
        j23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j23ActionPerformed(evt);
            }
        });

        j33.setMinimumSize(new java.awt.Dimension(6, 6));
        j33.setPreferredSize(new java.awt.Dimension(25, 25));
        j33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j33ActionPerformed(evt);
            }
        });

        j43.setMinimumSize(new java.awt.Dimension(6, 6));
        j43.setPreferredSize(new java.awt.Dimension(25, 25));
        j43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j43ActionPerformed(evt);
            }
        });

        j53.setMinimumSize(new java.awt.Dimension(6, 6));
        j53.setPreferredSize(new java.awt.Dimension(25, 25));
        j53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j53ActionPerformed(evt);
            }
        });

        j63.setMinimumSize(new java.awt.Dimension(6, 6));
        j63.setPreferredSize(new java.awt.Dimension(25, 25));
        j63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j63ActionPerformed(evt);
            }
        });

        j73.setMinimumSize(new java.awt.Dimension(6, 6));
        j73.setPreferredSize(new java.awt.Dimension(25, 25));
        j73.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j73ActionPerformed(evt);
            }
        });

        j83.setMinimumSize(new java.awt.Dimension(6, 6));
        j83.setPreferredSize(new java.awt.Dimension(25, 25));
        j83.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j83ActionPerformed(evt);
            }
        });

        j04.setMinimumSize(new java.awt.Dimension(6, 6));
        j04.setPreferredSize(new java.awt.Dimension(25, 25));
        j04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j04ActionPerformed(evt);
            }
        });

        j14.setMinimumSize(new java.awt.Dimension(6, 6));
        j14.setPreferredSize(new java.awt.Dimension(25, 25));
        j14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j14ActionPerformed(evt);
            }
        });

        j24.setMinimumSize(new java.awt.Dimension(6, 6));
        j24.setPreferredSize(new java.awt.Dimension(25, 25));
        j24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j24ActionPerformed(evt);
            }
        });

        j34.setMinimumSize(new java.awt.Dimension(6, 6));
        j34.setPreferredSize(new java.awt.Dimension(25, 25));
        j34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j34ActionPerformed(evt);
            }
        });

        j44.setMinimumSize(new java.awt.Dimension(6, 6));
        j44.setPreferredSize(new java.awt.Dimension(25, 25));
        j44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j44ActionPerformed(evt);
            }
        });

        j54.setMinimumSize(new java.awt.Dimension(6, 6));
        j54.setPreferredSize(new java.awt.Dimension(25, 25));
        j54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j54ActionPerformed(evt);
            }
        });

        j64.setMinimumSize(new java.awt.Dimension(6, 6));
        j64.setPreferredSize(new java.awt.Dimension(25, 25));
        j64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j64ActionPerformed(evt);
            }
        });

        j74.setMinimumSize(new java.awt.Dimension(6, 6));
        j74.setPreferredSize(new java.awt.Dimension(25, 25));
        j74.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j74ActionPerformed(evt);
            }
        });

        j84.setMinimumSize(new java.awt.Dimension(6, 6));
        j84.setPreferredSize(new java.awt.Dimension(25, 25));
        j84.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j84ActionPerformed(evt);
            }
        });

        j05.setMinimumSize(new java.awt.Dimension(6, 6));
        j05.setPreferredSize(new java.awt.Dimension(25, 25));
        j05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j05ActionPerformed(evt);
            }
        });

        j15.setMinimumSize(new java.awt.Dimension(6, 6));
        j15.setPreferredSize(new java.awt.Dimension(25, 25));
        j15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j15ActionPerformed(evt);
            }
        });

        j25.setMinimumSize(new java.awt.Dimension(6, 6));
        j25.setPreferredSize(new java.awt.Dimension(25, 25));
        j25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j25ActionPerformed(evt);
            }
        });

        j35.setMinimumSize(new java.awt.Dimension(6, 6));
        j35.setPreferredSize(new java.awt.Dimension(25, 25));
        j35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j35ActionPerformed(evt);
            }
        });

        j45.setMinimumSize(new java.awt.Dimension(6, 6));
        j45.setPreferredSize(new java.awt.Dimension(25, 25));
        j45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j45ActionPerformed(evt);
            }
        });

        j55.setMinimumSize(new java.awt.Dimension(6, 6));
        j55.setPreferredSize(new java.awt.Dimension(25, 25));
        j55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j55ActionPerformed(evt);
            }
        });

        j65.setMinimumSize(new java.awt.Dimension(6, 6));
        j65.setPreferredSize(new java.awt.Dimension(25, 25));
        j65.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j65ActionPerformed(evt);
            }
        });

        j75.setMinimumSize(new java.awt.Dimension(6, 6));
        j75.setPreferredSize(new java.awt.Dimension(25, 25));
        j75.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j75ActionPerformed(evt);
            }
        });

        j85.setMinimumSize(new java.awt.Dimension(6, 6));
        j85.setPreferredSize(new java.awt.Dimension(25, 25));
        j85.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j85ActionPerformed(evt);
            }
        });

        j06.setMinimumSize(new java.awt.Dimension(6, 6));
        j06.setPreferredSize(new java.awt.Dimension(25, 25));
        j06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j06ActionPerformed(evt);
            }
        });

        j16.setMinimumSize(new java.awt.Dimension(6, 6));
        j16.setPreferredSize(new java.awt.Dimension(25, 25));
        j16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j16ActionPerformed(evt);
            }
        });

        j26.setMinimumSize(new java.awt.Dimension(6, 6));
        j26.setPreferredSize(new java.awt.Dimension(25, 25));
        j26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j26ActionPerformed(evt);
            }
        });

        j36.setMinimumSize(new java.awt.Dimension(6, 6));
        j36.setPreferredSize(new java.awt.Dimension(25, 25));
        j36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j36ActionPerformed(evt);
            }
        });

        j46.setMinimumSize(new java.awt.Dimension(6, 6));
        j46.setPreferredSize(new java.awt.Dimension(25, 25));
        j46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j46ActionPerformed(evt);
            }
        });

        j56.setMinimumSize(new java.awt.Dimension(6, 6));
        j56.setPreferredSize(new java.awt.Dimension(25, 25));
        j56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j56ActionPerformed(evt);
            }
        });

        j66.setMinimumSize(new java.awt.Dimension(6, 6));
        j66.setPreferredSize(new java.awt.Dimension(25, 25));
        j66.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j66ActionPerformed(evt);
            }
        });

        j76.setMinimumSize(new java.awt.Dimension(6, 6));
        j76.setPreferredSize(new java.awt.Dimension(25, 25));
        j76.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j76ActionPerformed(evt);
            }
        });

        j86.setMinimumSize(new java.awt.Dimension(6, 6));
        j86.setPreferredSize(new java.awt.Dimension(25, 25));
        j86.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j86ActionPerformed(evt);
            }
        });

        j07.setMinimumSize(new java.awt.Dimension(6, 6));
        j07.setPreferredSize(new java.awt.Dimension(25, 25));
        j07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j07ActionPerformed(evt);
            }
        });

        j17.setMinimumSize(new java.awt.Dimension(6, 6));
        j17.setPreferredSize(new java.awt.Dimension(25, 25));
        j17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j17ActionPerformed(evt);
            }
        });

        j27.setMinimumSize(new java.awt.Dimension(6, 6));
        j27.setPreferredSize(new java.awt.Dimension(25, 25));
        j27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j27ActionPerformed(evt);
            }
        });

        j37.setMinimumSize(new java.awt.Dimension(6, 6));
        j37.setPreferredSize(new java.awt.Dimension(25, 25));
        j37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j37ActionPerformed(evt);
            }
        });

        j47.setMinimumSize(new java.awt.Dimension(6, 6));
        j47.setPreferredSize(new java.awt.Dimension(25, 25));
        j47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j47ActionPerformed(evt);
            }
        });

        j57.setMinimumSize(new java.awt.Dimension(6, 6));
        j57.setPreferredSize(new java.awt.Dimension(25, 25));
        j57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j57ActionPerformed(evt);
            }
        });

        j67.setMinimumSize(new java.awt.Dimension(6, 6));
        j67.setPreferredSize(new java.awt.Dimension(25, 25));
        j67.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j67ActionPerformed(evt);
            }
        });

        j77.setMinimumSize(new java.awt.Dimension(6, 6));
        j77.setPreferredSize(new java.awt.Dimension(25, 25));
        j77.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j77ActionPerformed(evt);
            }
        });

        j87.setMinimumSize(new java.awt.Dimension(6, 6));
        j87.setPreferredSize(new java.awt.Dimension(25, 25));
        j87.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j87ActionPerformed(evt);
            }
        });

        j08.setMinimumSize(new java.awt.Dimension(6, 6));
        j08.setPreferredSize(new java.awt.Dimension(25, 25));
        j08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j08ActionPerformed(evt);
            }
        });

        j18.setMinimumSize(new java.awt.Dimension(6, 6));
        j18.setPreferredSize(new java.awt.Dimension(25, 25));
        j18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j18ActionPerformed(evt);
            }
        });

        j28.setMinimumSize(new java.awt.Dimension(6, 6));
        j28.setPreferredSize(new java.awt.Dimension(25, 25));
        j28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j28ActionPerformed(evt);
            }
        });

        j38.setMinimumSize(new java.awt.Dimension(6, 6));
        j38.setPreferredSize(new java.awt.Dimension(25, 25));
        j38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j38ActionPerformed(evt);
            }
        });

        j48.setMinimumSize(new java.awt.Dimension(6, 6));
        j48.setPreferredSize(new java.awt.Dimension(25, 25));
        j48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j48ActionPerformed(evt);
            }
        });

        j58.setMinimumSize(new java.awt.Dimension(6, 6));
        j58.setPreferredSize(new java.awt.Dimension(25, 25));
        j58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j58ActionPerformed(evt);
            }
        });

        j68.setMinimumSize(new java.awt.Dimension(6, 6));
        j68.setPreferredSize(new java.awt.Dimension(25, 25));
        j68.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j68ActionPerformed(evt);
            }
        });

        j78.setMinimumSize(new java.awt.Dimension(6, 6));
        j78.setPreferredSize(new java.awt.Dimension(25, 25));
        j78.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j78ActionPerformed(evt);
            }
        });

        j88.setMinimumSize(new java.awt.Dimension(6, 6));
        j88.setPreferredSize(new java.awt.Dimension(25, 25));
        j88.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j88ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j70, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j80, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j71, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j81, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j72, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j82, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j73, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j83, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j64, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j74, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j84, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j65, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j75, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j85, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j06, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j66, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j76, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j86, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j07, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j57, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j67, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j77, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j87, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j08, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j58, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j68, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j78, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j88, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(j08, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j58, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j68, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j78, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j88, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(j07, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j57, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j67, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j77, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j87, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(j06, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j66, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j76, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j86, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(j05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j65, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j75, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j85, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(j04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j64, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j74, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j84, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(j03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j73, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j83, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(j02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j72, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j82, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(j01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j71, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j81, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(j00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j70, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j80, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void j00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j00ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j00ActionPerformed

    private void j10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j10ActionPerformed

    private void j20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j20ActionPerformed

    private void j30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j30ActionPerformed

    private void j40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j40ActionPerformed

    private void j50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j50ActionPerformed

    private void j60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j60ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j60ActionPerformed

    private void j70ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j70ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j70ActionPerformed

    private void j80ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j80ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j80ActionPerformed

    private void j01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j01ActionPerformed

    private void j11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j11ActionPerformed

    private void j21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j21ActionPerformed

    private void j31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j31ActionPerformed

    private void j41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j41ActionPerformed

    private void j51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j51ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j51ActionPerformed

    private void j61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j61ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j61ActionPerformed

    private void j71ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j71ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j71ActionPerformed

    private void j81ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j81ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j81ActionPerformed

    private void j02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j02ActionPerformed

    private void j12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j12ActionPerformed

    private void j22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j22ActionPerformed

    private void j32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j32ActionPerformed

    private void j42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j42ActionPerformed

    private void j52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j52ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j52ActionPerformed

    private void j62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j62ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j62ActionPerformed

    private void j72ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j72ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j72ActionPerformed

    private void j82ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j82ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j82ActionPerformed

    private void j03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j03ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j03ActionPerformed

    private void j13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j13ActionPerformed

    private void j23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j23ActionPerformed

    private void j33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j33ActionPerformed

    private void j43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j43ActionPerformed

    private void j53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j53ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j53ActionPerformed

    private void j63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j63ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j63ActionPerformed

    private void j73ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j73ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j73ActionPerformed

    private void j83ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j83ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j83ActionPerformed

    private void j04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j04ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j04ActionPerformed

    private void j14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j14ActionPerformed

    private void j24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j24ActionPerformed

    private void j34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j34ActionPerformed

    private void j44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j44ActionPerformed

    private void j54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j54ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j54ActionPerformed

    private void j64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j64ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j64ActionPerformed

    private void j74ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j74ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j74ActionPerformed

    private void j84ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j84ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j84ActionPerformed

    private void j05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j05ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j05ActionPerformed

    private void j15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j15ActionPerformed

    private void j25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j25ActionPerformed

    private void j35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j35ActionPerformed

    private void j45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j45ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j45ActionPerformed

    private void j55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j55ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j55ActionPerformed

    private void j65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j65ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j65ActionPerformed

    private void j75ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j75ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j75ActionPerformed

    private void j85ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j85ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j85ActionPerformed

    private void j06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j06ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j06ActionPerformed

    private void j16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j16ActionPerformed

    private void j26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j26ActionPerformed

    private void j36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j36ActionPerformed

    private void j46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j46ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j46ActionPerformed

    private void j56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j56ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j56ActionPerformed

    private void j66ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j66ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j66ActionPerformed

    private void j76ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j76ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j76ActionPerformed

    private void j86ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j86ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j86ActionPerformed

    private void j07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j07ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j07ActionPerformed

    private void j17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j17ActionPerformed

    private void j27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j27ActionPerformed

    private void j37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j37ActionPerformed

    private void j47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j47ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j47ActionPerformed

    private void j57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j57ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j57ActionPerformed

    private void j67ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j67ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j67ActionPerformed

    private void j77ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j77ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j77ActionPerformed

    private void j87ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j87ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j87ActionPerformed

    private void j08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j08ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j08ActionPerformed

    private void j18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j18ActionPerformed

    private void j28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j28ActionPerformed

    private void j38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j38ActionPerformed

    private void j48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j48ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j48ActionPerformed

    private void j58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j58ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j58ActionPerformed

    private void j68ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j68ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j68ActionPerformed

    private void j78ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j78ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j78ActionPerformed

    private void j88ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j88ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j88ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField j00;
    private javax.swing.JTextField j01;
    private javax.swing.JTextField j02;
    private javax.swing.JTextField j03;
    private javax.swing.JTextField j04;
    private javax.swing.JTextField j05;
    private javax.swing.JTextField j06;
    private javax.swing.JTextField j07;
    private javax.swing.JTextField j08;
    private javax.swing.JTextField j10;
    private javax.swing.JTextField j11;
    private javax.swing.JTextField j12;
    private javax.swing.JTextField j13;
    private javax.swing.JTextField j14;
    private javax.swing.JTextField j15;
    private javax.swing.JTextField j16;
    private javax.swing.JTextField j17;
    private javax.swing.JTextField j18;
    private javax.swing.JTextField j20;
    private javax.swing.JTextField j21;
    private javax.swing.JTextField j22;
    private javax.swing.JTextField j23;
    private javax.swing.JTextField j24;
    private javax.swing.JTextField j25;
    private javax.swing.JTextField j26;
    private javax.swing.JTextField j27;
    private javax.swing.JTextField j28;
    private javax.swing.JTextField j30;
    private javax.swing.JTextField j31;
    private javax.swing.JTextField j32;
    private javax.swing.JTextField j33;
    private javax.swing.JTextField j34;
    private javax.swing.JTextField j35;
    private javax.swing.JTextField j36;
    private javax.swing.JTextField j37;
    private javax.swing.JTextField j38;
    private javax.swing.JTextField j40;
    private javax.swing.JTextField j41;
    private javax.swing.JTextField j42;
    private javax.swing.JTextField j43;
    private javax.swing.JTextField j44;
    private javax.swing.JTextField j45;
    private javax.swing.JTextField j46;
    private javax.swing.JTextField j47;
    private javax.swing.JTextField j48;
    private javax.swing.JTextField j50;
    private javax.swing.JTextField j51;
    private javax.swing.JTextField j52;
    private javax.swing.JTextField j53;
    private javax.swing.JTextField j54;
    private javax.swing.JTextField j55;
    private javax.swing.JTextField j56;
    private javax.swing.JTextField j57;
    private javax.swing.JTextField j58;
    private javax.swing.JTextField j60;
    private javax.swing.JTextField j61;
    private javax.swing.JTextField j62;
    private javax.swing.JTextField j63;
    private javax.swing.JTextField j64;
    private javax.swing.JTextField j65;
    private javax.swing.JTextField j66;
    private javax.swing.JTextField j67;
    private javax.swing.JTextField j68;
    private javax.swing.JTextField j70;
    private javax.swing.JTextField j71;
    private javax.swing.JTextField j72;
    private javax.swing.JTextField j73;
    private javax.swing.JTextField j74;
    private javax.swing.JTextField j75;
    private javax.swing.JTextField j76;
    private javax.swing.JTextField j77;
    private javax.swing.JTextField j78;
    private javax.swing.JTextField j80;
    private javax.swing.JTextField j81;
    private javax.swing.JTextField j82;
    private javax.swing.JTextField j83;
    private javax.swing.JTextField j84;
    private javax.swing.JTextField j85;
    private javax.swing.JTextField j86;
    private javax.swing.JTextField j87;
    private javax.swing.JTextField j88;
    // End of variables declaration//GEN-END:variables
}
