/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Generator;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class GUI extends javax.swing.JFrame {
    
    HashMap<String,JTextField> cells = new HashMap<>();
    private final int max_size = 9;
    private static Generator generator;
    private KeyListener keyListener;
    public GUI() {
        initComponents();
        
        generator = new Generator();
        initializeHashMap();
        addKeyListeners();
        while(!generator.createPuzzle());
        setRandomCells();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        j64 = new javax.swing.JTextField();
        j74 = new javax.swing.JTextField();
        j84 = new javax.swing.JTextField();
        j05 = new javax.swing.JTextField();
        j15 = new javax.swing.JTextField();
        j25 = new javax.swing.JTextField();
        j35 = new javax.swing.JTextField();
        j45 = new javax.swing.JTextField();
        j55 = new javax.swing.JTextField();
        j65 = new javax.swing.JTextField();
        j80 = new javax.swing.JTextField();
        j75 = new javax.swing.JTextField();
        j01 = new javax.swing.JTextField();
        j85 = new javax.swing.JTextField();
        j11 = new javax.swing.JTextField();
        j06 = new javax.swing.JTextField();
        j21 = new javax.swing.JTextField();
        j16 = new javax.swing.JTextField();
        j31 = new javax.swing.JTextField();
        j26 = new javax.swing.JTextField();
        j41 = new javax.swing.JTextField();
        j36 = new javax.swing.JTextField();
        j51 = new javax.swing.JTextField();
        j61 = new javax.swing.JTextField();
        j71 = new javax.swing.JTextField();
        j81 = new javax.swing.JTextField();
        j00 = new javax.swing.JTextField();
        j10 = new javax.swing.JTextField();
        j20 = new javax.swing.JTextField();
        j30 = new javax.swing.JTextField();
        j40 = new javax.swing.JTextField();
        j50 = new javax.swing.JTextField();
        j60 = new javax.swing.JTextField();
        j70 = new javax.swing.JTextField();
        j46 = new javax.swing.JTextField();
        j56 = new javax.swing.JTextField();
        j66 = new javax.swing.JTextField();
        j76 = new javax.swing.JTextField();
        j02 = new javax.swing.JTextField();
        j86 = new javax.swing.JTextField();
        j12 = new javax.swing.JTextField();
        j07 = new javax.swing.JTextField();
        j22 = new javax.swing.JTextField();
        j17 = new javax.swing.JTextField();
        j32 = new javax.swing.JTextField();
        j27 = new javax.swing.JTextField();
        j42 = new javax.swing.JTextField();
        j37 = new javax.swing.JTextField();
        j52 = new javax.swing.JTextField();
        j47 = new javax.swing.JTextField();
        j62 = new javax.swing.JTextField();
        j72 = new javax.swing.JTextField();
        j82 = new javax.swing.JTextField();
        j03 = new javax.swing.JTextField();
        j57 = new javax.swing.JTextField();
        j67 = new javax.swing.JTextField();
        j77 = new javax.swing.JTextField();
        j87 = new javax.swing.JTextField();
        j13 = new javax.swing.JTextField();
        j08 = new javax.swing.JTextField();
        j23 = new javax.swing.JTextField();
        j18 = new javax.swing.JTextField();
        j33 = new javax.swing.JTextField();
        j28 = new javax.swing.JTextField();
        j43 = new javax.swing.JTextField();
        j38 = new javax.swing.JTextField();
        j53 = new javax.swing.JTextField();
        j48 = new javax.swing.JTextField();
        j63 = new javax.swing.JTextField();
        j58 = new javax.swing.JTextField();
        j73 = new javax.swing.JTextField();
        j83 = new javax.swing.JTextField();
        j04 = new javax.swing.JTextField();
        j14 = new javax.swing.JTextField();
        j68 = new javax.swing.JTextField();
        j78 = new javax.swing.JTextField();
        j88 = new javax.swing.JTextField();
        j24 = new javax.swing.JTextField();
        j34 = new javax.swing.JTextField();
        j44 = new javax.swing.JTextField();
        j54 = new javax.swing.JTextField();
        submitSudoku = new javax.swing.JButton();
        Heading = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        j64.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j64.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j64.setMinimumSize(new java.awt.Dimension(6, 6));
        j64.setPreferredSize(new java.awt.Dimension(40, 40));
        j64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j64ActionPerformed(evt);
            }
        });
        getContentPane().add(j64, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 335, -1, -1));

        j74.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j74.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j74.setMinimumSize(new java.awt.Dimension(6, 6));
        j74.setPreferredSize(new java.awt.Dimension(40, 40));
        j74.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j74ActionPerformed(evt);
            }
        });
        getContentPane().add(j74, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 381, -1, -1));

        j84.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j84.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j84.setMinimumSize(new java.awt.Dimension(6, 6));
        j84.setPreferredSize(new java.awt.Dimension(40, 40));
        j84.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j84ActionPerformed(evt);
            }
        });
        getContentPane().add(j84, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 427, -1, -1));

        j05.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j05.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j05.setMinimumSize(new java.awt.Dimension(6, 6));
        j05.setPreferredSize(new java.awt.Dimension(40, 40));
        j05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j05ActionPerformed(evt);
            }
        });
        getContentPane().add(j05, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 59, -1, -1));

        j15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j15.setMinimumSize(new java.awt.Dimension(6, 6));
        j15.setPreferredSize(new java.awt.Dimension(40, 40));
        j15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j15ActionPerformed(evt);
            }
        });
        getContentPane().add(j15, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 105, -1, -1));

        j25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j25.setMinimumSize(new java.awt.Dimension(6, 6));
        j25.setPreferredSize(new java.awt.Dimension(40, 40));
        j25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j25ActionPerformed(evt);
            }
        });
        getContentPane().add(j25, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 151, -1, -1));

        j35.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j35.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j35.setMinimumSize(new java.awt.Dimension(6, 6));
        j35.setPreferredSize(new java.awt.Dimension(40, 40));
        j35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j35ActionPerformed(evt);
            }
        });
        getContentPane().add(j35, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 197, -1, -1));

        j45.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j45.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j45.setMinimumSize(new java.awt.Dimension(6, 6));
        j45.setPreferredSize(new java.awt.Dimension(40, 40));
        j45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j45ActionPerformed(evt);
            }
        });
        getContentPane().add(j45, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 243, -1, -1));

        j55.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j55.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j55.setMinimumSize(new java.awt.Dimension(6, 6));
        j55.setPreferredSize(new java.awt.Dimension(40, 40));
        j55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j55ActionPerformed(evt);
            }
        });
        getContentPane().add(j55, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 289, -1, -1));

        j65.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j65.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j65.setMinimumSize(new java.awt.Dimension(6, 6));
        j65.setPreferredSize(new java.awt.Dimension(40, 40));
        j65.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j65ActionPerformed(evt);
            }
        });
        getContentPane().add(j65, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 335, -1, -1));

        j80.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j80.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j80.setMinimumSize(new java.awt.Dimension(6, 6));
        j80.setPreferredSize(new java.awt.Dimension(40, 40));
        j80.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j80ActionPerformed(evt);
            }
        });
        getContentPane().add(j80, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 427, -1, -1));

        j75.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j75.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j75.setMinimumSize(new java.awt.Dimension(6, 6));
        j75.setPreferredSize(new java.awt.Dimension(40, 40));
        j75.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j75ActionPerformed(evt);
            }
        });
        getContentPane().add(j75, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 381, -1, -1));

        j01.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j01.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j01.setMinimumSize(new java.awt.Dimension(6, 6));
        j01.setPreferredSize(new java.awt.Dimension(40, 40));
        j01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j01ActionPerformed(evt);
            }
        });
        getContentPane().add(j01, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 59, -1, -1));

        j85.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j85.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j85.setMinimumSize(new java.awt.Dimension(6, 6));
        j85.setPreferredSize(new java.awt.Dimension(40, 40));
        j85.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j85ActionPerformed(evt);
            }
        });
        getContentPane().add(j85, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 427, -1, -1));

        j11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j11.setMinimumSize(new java.awt.Dimension(6, 6));
        j11.setPreferredSize(new java.awt.Dimension(40, 40));
        j11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j11ActionPerformed(evt);
            }
        });
        getContentPane().add(j11, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 105, -1, -1));

        j06.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j06.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j06.setMinimumSize(new java.awt.Dimension(6, 6));
        j06.setPreferredSize(new java.awt.Dimension(40, 40));
        j06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j06ActionPerformed(evt);
            }
        });
        getContentPane().add(j06, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 59, -1, -1));

        j21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j21.setMinimumSize(new java.awt.Dimension(6, 6));
        j21.setPreferredSize(new java.awt.Dimension(40, 40));
        j21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j21ActionPerformed(evt);
            }
        });
        getContentPane().add(j21, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 151, -1, -1));

        j16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j16.setMinimumSize(new java.awt.Dimension(6, 6));
        j16.setPreferredSize(new java.awt.Dimension(40, 40));
        j16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j16ActionPerformed(evt);
            }
        });
        getContentPane().add(j16, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 105, -1, -1));

        j31.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j31.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j31.setMinimumSize(new java.awt.Dimension(6, 6));
        j31.setPreferredSize(new java.awt.Dimension(40, 40));
        j31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j31ActionPerformed(evt);
            }
        });
        getContentPane().add(j31, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 197, -1, -1));

        j26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j26.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j26.setMinimumSize(new java.awt.Dimension(6, 6));
        j26.setPreferredSize(new java.awt.Dimension(40, 40));
        j26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j26ActionPerformed(evt);
            }
        });
        getContentPane().add(j26, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 151, -1, -1));

        j41.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j41.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j41.setMinimumSize(new java.awt.Dimension(6, 6));
        j41.setPreferredSize(new java.awt.Dimension(40, 40));
        j41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j41ActionPerformed(evt);
            }
        });
        getContentPane().add(j41, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 243, -1, -1));

        j36.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j36.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j36.setMinimumSize(new java.awt.Dimension(6, 6));
        j36.setPreferredSize(new java.awt.Dimension(40, 40));
        j36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j36ActionPerformed(evt);
            }
        });
        getContentPane().add(j36, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 197, -1, -1));

        j51.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j51.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j51.setMinimumSize(new java.awt.Dimension(6, 6));
        j51.setPreferredSize(new java.awt.Dimension(40, 40));
        j51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j51ActionPerformed(evt);
            }
        });
        getContentPane().add(j51, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 289, -1, -1));

        j61.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j61.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j61.setMinimumSize(new java.awt.Dimension(6, 6));
        j61.setPreferredSize(new java.awt.Dimension(40, 40));
        j61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j61ActionPerformed(evt);
            }
        });
        getContentPane().add(j61, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 335, -1, -1));

        j71.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j71.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j71.setMinimumSize(new java.awt.Dimension(6, 6));
        j71.setPreferredSize(new java.awt.Dimension(40, 40));
        j71.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j71ActionPerformed(evt);
            }
        });
        getContentPane().add(j71, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 381, -1, -1));

        j81.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j81.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j81.setMinimumSize(new java.awt.Dimension(6, 6));
        j81.setPreferredSize(new java.awt.Dimension(40, 40));
        j81.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j81ActionPerformed(evt);
            }
        });
        getContentPane().add(j81, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 427, -1, -1));

        j00.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j00.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j00.setMinimumSize(new java.awt.Dimension(6, 6));
        j00.setPreferredSize(new java.awt.Dimension(40, 40));
        j00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j00ActionPerformed(evt);
            }
        });
        getContentPane().add(j00, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 59, -1, -1));

        j10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j10.setMinimumSize(new java.awt.Dimension(6, 6));
        j10.setPreferredSize(new java.awt.Dimension(40, 40));
        j10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j10ActionPerformed(evt);
            }
        });
        getContentPane().add(j10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 105, -1, -1));

        j20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j20.setMinimumSize(new java.awt.Dimension(6, 6));
        j20.setPreferredSize(new java.awt.Dimension(40, 40));
        j20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j20ActionPerformed(evt);
            }
        });
        getContentPane().add(j20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 151, -1, -1));

        j30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j30.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j30.setMinimumSize(new java.awt.Dimension(6, 6));
        j30.setPreferredSize(new java.awt.Dimension(40, 40));
        j30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j30ActionPerformed(evt);
            }
        });
        getContentPane().add(j30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 197, -1, -1));

        j40.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j40.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j40.setMinimumSize(new java.awt.Dimension(6, 6));
        j40.setPreferredSize(new java.awt.Dimension(40, 40));
        j40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j40ActionPerformed(evt);
            }
        });
        getContentPane().add(j40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 243, -1, -1));

        j50.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j50.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j50.setMinimumSize(new java.awt.Dimension(6, 6));
        j50.setPreferredSize(new java.awt.Dimension(40, 40));
        j50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j50ActionPerformed(evt);
            }
        });
        getContentPane().add(j50, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 289, -1, -1));

        j60.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j60.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j60.setMinimumSize(new java.awt.Dimension(6, 6));
        j60.setPreferredSize(new java.awt.Dimension(40, 40));
        j60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j60ActionPerformed(evt);
            }
        });
        getContentPane().add(j60, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 335, -1, -1));

        j70.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j70.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j70.setMinimumSize(new java.awt.Dimension(6, 6));
        j70.setPreferredSize(new java.awt.Dimension(40, 40));
        j70.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j70ActionPerformed(evt);
            }
        });
        getContentPane().add(j70, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 381, -1, -1));

        j46.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j46.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j46.setMinimumSize(new java.awt.Dimension(6, 6));
        j46.setPreferredSize(new java.awt.Dimension(40, 40));
        j46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j46ActionPerformed(evt);
            }
        });
        getContentPane().add(j46, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 243, -1, -1));

        j56.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j56.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j56.setMinimumSize(new java.awt.Dimension(6, 6));
        j56.setPreferredSize(new java.awt.Dimension(40, 40));
        j56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j56ActionPerformed(evt);
            }
        });
        getContentPane().add(j56, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 289, -1, -1));

        j66.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j66.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j66.setMinimumSize(new java.awt.Dimension(6, 6));
        j66.setPreferredSize(new java.awt.Dimension(40, 40));
        j66.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j66ActionPerformed(evt);
            }
        });
        getContentPane().add(j66, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 335, -1, -1));

        j76.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j76.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j76.setMinimumSize(new java.awt.Dimension(6, 6));
        j76.setPreferredSize(new java.awt.Dimension(40, 40));
        j76.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j76ActionPerformed(evt);
            }
        });
        getContentPane().add(j76, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 381, -1, -1));

        j02.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j02.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j02.setMinimumSize(new java.awt.Dimension(6, 6));
        j02.setPreferredSize(new java.awt.Dimension(40, 40));
        j02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j02ActionPerformed(evt);
            }
        });
        getContentPane().add(j02, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 59, -1, -1));

        j86.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j86.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j86.setMinimumSize(new java.awt.Dimension(6, 6));
        j86.setPreferredSize(new java.awt.Dimension(40, 40));
        j86.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j86ActionPerformed(evt);
            }
        });
        getContentPane().add(j86, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 427, -1, -1));

        j12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j12.setMinimumSize(new java.awt.Dimension(6, 6));
        j12.setPreferredSize(new java.awt.Dimension(40, 40));
        j12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j12ActionPerformed(evt);
            }
        });
        getContentPane().add(j12, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 105, -1, -1));

        j07.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j07.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j07.setMinimumSize(new java.awt.Dimension(6, 6));
        j07.setPreferredSize(new java.awt.Dimension(40, 40));
        j07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j07ActionPerformed(evt);
            }
        });
        getContentPane().add(j07, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 59, -1, -1));

        j22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j22.setMinimumSize(new java.awt.Dimension(6, 6));
        j22.setPreferredSize(new java.awt.Dimension(40, 40));
        j22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j22ActionPerformed(evt);
            }
        });
        getContentPane().add(j22, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 151, -1, -1));

        j17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j17.setMinimumSize(new java.awt.Dimension(6, 6));
        j17.setPreferredSize(new java.awt.Dimension(40, 40));
        j17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j17ActionPerformed(evt);
            }
        });
        getContentPane().add(j17, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 105, -1, -1));

        j32.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j32.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j32.setMinimumSize(new java.awt.Dimension(6, 6));
        j32.setPreferredSize(new java.awt.Dimension(40, 40));
        j32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j32ActionPerformed(evt);
            }
        });
        getContentPane().add(j32, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 197, -1, -1));

        j27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j27.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j27.setMinimumSize(new java.awt.Dimension(6, 6));
        j27.setPreferredSize(new java.awt.Dimension(40, 40));
        j27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j27ActionPerformed(evt);
            }
        });
        getContentPane().add(j27, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 151, -1, -1));

        j42.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j42.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j42.setMinimumSize(new java.awt.Dimension(6, 6));
        j42.setPreferredSize(new java.awt.Dimension(40, 40));
        j42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j42ActionPerformed(evt);
            }
        });
        getContentPane().add(j42, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 243, -1, -1));

        j37.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j37.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j37.setMinimumSize(new java.awt.Dimension(6, 6));
        j37.setPreferredSize(new java.awt.Dimension(40, 40));
        j37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j37ActionPerformed(evt);
            }
        });
        getContentPane().add(j37, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 197, -1, -1));

        j52.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j52.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j52.setMinimumSize(new java.awt.Dimension(6, 6));
        j52.setPreferredSize(new java.awt.Dimension(40, 40));
        j52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j52ActionPerformed(evt);
            }
        });
        getContentPane().add(j52, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 289, -1, -1));

        j47.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j47.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j47.setMinimumSize(new java.awt.Dimension(6, 6));
        j47.setPreferredSize(new java.awt.Dimension(40, 40));
        j47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j47ActionPerformed(evt);
            }
        });
        getContentPane().add(j47, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 243, -1, -1));

        j62.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j62.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j62.setMinimumSize(new java.awt.Dimension(6, 6));
        j62.setPreferredSize(new java.awt.Dimension(40, 40));
        j62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j62ActionPerformed(evt);
            }
        });
        getContentPane().add(j62, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 335, -1, -1));

        j72.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j72.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j72.setMinimumSize(new java.awt.Dimension(6, 6));
        j72.setPreferredSize(new java.awt.Dimension(40, 40));
        j72.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j72ActionPerformed(evt);
            }
        });
        getContentPane().add(j72, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 381, -1, -1));

        j82.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j82.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j82.setMinimumSize(new java.awt.Dimension(6, 6));
        j82.setPreferredSize(new java.awt.Dimension(40, 40));
        j82.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j82ActionPerformed(evt);
            }
        });
        getContentPane().add(j82, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 427, -1, -1));

        j03.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j03.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j03.setMinimumSize(new java.awt.Dimension(6, 6));
        j03.setPreferredSize(new java.awt.Dimension(40, 40));
        j03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j03ActionPerformed(evt);
            }
        });
        getContentPane().add(j03, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 59, -1, -1));

        j57.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j57.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j57.setMinimumSize(new java.awt.Dimension(6, 6));
        j57.setPreferredSize(new java.awt.Dimension(40, 40));
        j57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j57ActionPerformed(evt);
            }
        });
        getContentPane().add(j57, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 289, -1, -1));

        j67.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j67.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j67.setMinimumSize(new java.awt.Dimension(6, 6));
        j67.setPreferredSize(new java.awt.Dimension(40, 40));
        j67.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j67ActionPerformed(evt);
            }
        });
        getContentPane().add(j67, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 335, -1, -1));

        j77.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j77.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j77.setMinimumSize(new java.awt.Dimension(6, 6));
        j77.setPreferredSize(new java.awt.Dimension(40, 40));
        j77.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j77ActionPerformed(evt);
            }
        });
        getContentPane().add(j77, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 381, -1, -1));

        j87.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j87.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j87.setMinimumSize(new java.awt.Dimension(6, 6));
        j87.setPreferredSize(new java.awt.Dimension(40, 40));
        j87.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j87ActionPerformed(evt);
            }
        });
        getContentPane().add(j87, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 427, -1, -1));

        j13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j13.setMinimumSize(new java.awt.Dimension(6, 6));
        j13.setPreferredSize(new java.awt.Dimension(40, 40));
        j13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j13ActionPerformed(evt);
            }
        });
        getContentPane().add(j13, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 105, -1, -1));

        j08.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j08.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j08.setMinimumSize(new java.awt.Dimension(6, 6));
        j08.setPreferredSize(new java.awt.Dimension(40, 40));
        j08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j08ActionPerformed(evt);
            }
        });
        getContentPane().add(j08, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 59, -1, -1));

        j23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j23.setMinimumSize(new java.awt.Dimension(6, 6));
        j23.setPreferredSize(new java.awt.Dimension(40, 40));
        j23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j23ActionPerformed(evt);
            }
        });
        getContentPane().add(j23, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 151, -1, -1));

        j18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j18.setMinimumSize(new java.awt.Dimension(6, 6));
        j18.setPreferredSize(new java.awt.Dimension(40, 40));
        j18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j18ActionPerformed(evt);
            }
        });
        getContentPane().add(j18, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 105, -1, -1));

        j33.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j33.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j33.setMinimumSize(new java.awt.Dimension(6, 6));
        j33.setPreferredSize(new java.awt.Dimension(40, 40));
        j33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j33ActionPerformed(evt);
            }
        });
        getContentPane().add(j33, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 197, -1, -1));

        j28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j28.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j28.setMinimumSize(new java.awt.Dimension(6, 6));
        j28.setPreferredSize(new java.awt.Dimension(40, 40));
        j28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j28ActionPerformed(evt);
            }
        });
        getContentPane().add(j28, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 151, -1, -1));

        j43.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j43.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j43.setMinimumSize(new java.awt.Dimension(6, 6));
        j43.setPreferredSize(new java.awt.Dimension(40, 40));
        j43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j43ActionPerformed(evt);
            }
        });
        getContentPane().add(j43, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 243, -1, -1));

        j38.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j38.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j38.setMinimumSize(new java.awt.Dimension(6, 6));
        j38.setPreferredSize(new java.awt.Dimension(40, 40));
        j38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j38ActionPerformed(evt);
            }
        });
        getContentPane().add(j38, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 197, -1, -1));

        j53.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j53.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j53.setMinimumSize(new java.awt.Dimension(6, 6));
        j53.setPreferredSize(new java.awt.Dimension(40, 40));
        j53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j53ActionPerformed(evt);
            }
        });
        getContentPane().add(j53, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 289, -1, -1));

        j48.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j48.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j48.setMinimumSize(new java.awt.Dimension(6, 6));
        j48.setPreferredSize(new java.awt.Dimension(40, 40));
        j48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j48ActionPerformed(evt);
            }
        });
        getContentPane().add(j48, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 243, -1, -1));

        j63.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j63.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j63.setMinimumSize(new java.awt.Dimension(6, 6));
        j63.setPreferredSize(new java.awt.Dimension(40, 40));
        j63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j63ActionPerformed(evt);
            }
        });
        getContentPane().add(j63, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 335, -1, -1));

        j58.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j58.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j58.setMinimumSize(new java.awt.Dimension(6, 6));
        j58.setPreferredSize(new java.awt.Dimension(40, 40));
        j58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j58ActionPerformed(evt);
            }
        });
        getContentPane().add(j58, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 289, -1, -1));

        j73.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j73.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j73.setMinimumSize(new java.awt.Dimension(6, 6));
        j73.setPreferredSize(new java.awt.Dimension(40, 40));
        j73.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j73ActionPerformed(evt);
            }
        });
        getContentPane().add(j73, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 381, -1, -1));

        j83.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j83.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j83.setMinimumSize(new java.awt.Dimension(6, 6));
        j83.setPreferredSize(new java.awt.Dimension(40, 40));
        j83.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j83ActionPerformed(evt);
            }
        });
        getContentPane().add(j83, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 427, -1, -1));

        j04.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j04.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j04.setMinimumSize(new java.awt.Dimension(6, 6));
        j04.setPreferredSize(new java.awt.Dimension(40, 40));
        j04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j04ActionPerformed(evt);
            }
        });
        getContentPane().add(j04, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 59, -1, -1));

        j14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j14.setMinimumSize(new java.awt.Dimension(6, 6));
        j14.setPreferredSize(new java.awt.Dimension(40, 40));
        j14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j14ActionPerformed(evt);
            }
        });
        getContentPane().add(j14, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 105, -1, -1));

        j68.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j68.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j68.setMinimumSize(new java.awt.Dimension(6, 6));
        j68.setPreferredSize(new java.awt.Dimension(40, 40));
        j68.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j68ActionPerformed(evt);
            }
        });
        getContentPane().add(j68, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 335, -1, -1));

        j78.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j78.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j78.setMinimumSize(new java.awt.Dimension(6, 6));
        j78.setPreferredSize(new java.awt.Dimension(40, 40));
        j78.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j78ActionPerformed(evt);
            }
        });
        getContentPane().add(j78, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 381, -1, -1));

        j88.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j88.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j88.setMinimumSize(new java.awt.Dimension(6, 6));
        j88.setPreferredSize(new java.awt.Dimension(40, 40));
        j88.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j88ActionPerformed(evt);
            }
        });
        getContentPane().add(j88, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 427, -1, -1));

        j24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j24.setMinimumSize(new java.awt.Dimension(6, 6));
        j24.setPreferredSize(new java.awt.Dimension(40, 40));
        j24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j24ActionPerformed(evt);
            }
        });
        getContentPane().add(j24, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 151, -1, -1));

        j34.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j34.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j34.setMinimumSize(new java.awt.Dimension(6, 6));
        j34.setPreferredSize(new java.awt.Dimension(40, 40));
        j34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j34ActionPerformed(evt);
            }
        });
        getContentPane().add(j34, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 197, -1, -1));

        j44.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j44.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j44.setMinimumSize(new java.awt.Dimension(6, 6));
        j44.setPreferredSize(new java.awt.Dimension(40, 40));
        j44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j44ActionPerformed(evt);
            }
        });
        getContentPane().add(j44, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 243, -1, -1));

        j54.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        j54.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j54.setMinimumSize(new java.awt.Dimension(6, 6));
        j54.setPreferredSize(new java.awt.Dimension(40, 40));
        j54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j54ActionPerformed(evt);
            }
        });
        getContentPane().add(j54, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 289, -1, -1));

        submitSudoku.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        submitSudoku.setText("Submit");
        submitSudoku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitSudokuActionPerformed(evt);
            }
        });
        getContentPane().add(submitSudoku, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 132, -1));

        Heading.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        Heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Heading.setText("Sudoku");
        getContentPane().add(Heading, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 0, 316, 53));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Generator/Back.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 35, 450, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void j64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j64ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j64ActionPerformed

    private void j74ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j74ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j74ActionPerformed

    private void j84ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j84ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j84ActionPerformed

    private void j05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j05ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j05ActionPerformed

    private void j15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j15ActionPerformed

    private void j25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j25ActionPerformed

    private void j35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j35ActionPerformed

    private void j45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j45ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j45ActionPerformed

    private void j55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j55ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j55ActionPerformed

    private void j65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j65ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j65ActionPerformed

    private void j80ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j80ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j80ActionPerformed

    private void j75ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j75ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j75ActionPerformed

    private void j01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j01ActionPerformed

    private void j85ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j85ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j85ActionPerformed

    private void j11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j11ActionPerformed

    private void j06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j06ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j06ActionPerformed

    private void j21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j21ActionPerformed

    private void j16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j16ActionPerformed

    private void j31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j31ActionPerformed

    private void j26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j26ActionPerformed

    private void j41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j41ActionPerformed

    private void j36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j36ActionPerformed

    private void j51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j51ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j51ActionPerformed

    private void j61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j61ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j61ActionPerformed

    private void j71ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j71ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j71ActionPerformed

    private void j81ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j81ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j81ActionPerformed

    private void j00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j00ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j00ActionPerformed

    private void j10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j10ActionPerformed

    private void j20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j20ActionPerformed

    private void j30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j30ActionPerformed

    private void j40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j40ActionPerformed

    private void j50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j50ActionPerformed

    private void j60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j60ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j60ActionPerformed

    private void j70ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j70ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j70ActionPerformed

    private void j46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j46ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j46ActionPerformed

    private void j56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j56ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j56ActionPerformed

    private void j66ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j66ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j66ActionPerformed

    private void j76ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j76ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j76ActionPerformed

    private void j02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j02ActionPerformed

    private void j86ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j86ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j86ActionPerformed

    private void j12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j12ActionPerformed

    private void j07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j07ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j07ActionPerformed

    private void j22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j22ActionPerformed

    private void j17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j17ActionPerformed

    private void j32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j32ActionPerformed

    private void j27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j27ActionPerformed

    private void j42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j42ActionPerformed

    private void j37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j37ActionPerformed

    private void j52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j52ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j52ActionPerformed

    private void j47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j47ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j47ActionPerformed

    private void j62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j62ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j62ActionPerformed

    private void j72ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j72ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j72ActionPerformed

    private void j82ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j82ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j82ActionPerformed

    private void j03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j03ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j03ActionPerformed

    private void j57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j57ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j57ActionPerformed

    private void j67ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j67ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j67ActionPerformed

    private void j77ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j77ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j77ActionPerformed

    private void j87ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j87ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j87ActionPerformed

    private void j13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j13ActionPerformed

    private void j08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j08ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j08ActionPerformed

    private void j23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j23ActionPerformed

    private void j18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j18ActionPerformed

    private void j33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j33ActionPerformed

    private void j28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j28ActionPerformed

    private void j43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j43ActionPerformed

    private void j38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j38ActionPerformed

    private void j53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j53ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j53ActionPerformed

    private void j48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j48ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j48ActionPerformed

    private void j63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j63ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j63ActionPerformed

    private void j58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j58ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j58ActionPerformed

    private void j73ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j73ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j73ActionPerformed

    private void j83ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j83ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j83ActionPerformed

    private void j04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j04ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j04ActionPerformed

    private void j14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j14ActionPerformed

    private void j68ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j68ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j68ActionPerformed

    private void j78ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j78ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j78ActionPerformed

    private void j88ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j88ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j88ActionPerformed

    private void j24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j24ActionPerformed

    private void j34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j34ActionPerformed

    private void j44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j44ActionPerformed

    private void j54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j54ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j54ActionPerformed

    
    public void initializeHashMap(){
        
        /**
         * Objective: Store all the JTextFields in a HashMap for convenient access and operations
         * Input: NULL
         * Output: NULL
         */
        
        //First Row
        cells.put("j00",j00);
        cells.put("j01",j01);
        cells.put("j02",j02);
        cells.put("j03",j03);
        cells.put("j04",j04);
        cells.put("j05",j05);
        cells.put("j06",j06);
        cells.put("j07",j07);
        cells.put("j08",j08);
        
        //Second Row
        cells.put("j10",j10);
        cells.put("j11",j11);
        cells.put("j12",j12);
        cells.put("j13",j13);
        cells.put("j14",j14);
        cells.put("j15",j15);
        cells.put("j16",j16);
        cells.put("j17",j17);
        cells.put("j18",j18);
        
        //Third Row
        cells.put("j20",j20);
        cells.put("j21",j21);
        cells.put("j22",j22);
        cells.put("j23",j23);
        cells.put("j24",j24);
        cells.put("j25",j25);
        cells.put("j26",j26);
        cells.put("j27",j27);
        cells.put("j28",j28);
        
        //Fourth Row
        cells.put("j30",j30);
        cells.put("j31",j31);
        cells.put("j32",j32);
        cells.put("j33",j33);
        cells.put("j34",j34);
        cells.put("j35",j35);
        cells.put("j36",j36);
        cells.put("j37",j37);
        cells.put("j38",j38);
        
        //Fifth Row
        cells.put("j40",j40);
        cells.put("j41",j41);
        cells.put("j42",j42);
        cells.put("j43",j43);
        cells.put("j44",j44);
        cells.put("j45",j45);
        cells.put("j46",j46);
        cells.put("j47",j47);
        cells.put("j48",j48);
        
        //Sixth Row
        cells.put("j50",j50);
        cells.put("j51",j51);
        cells.put("j52",j52);
        cells.put("j53",j53);
        cells.put("j54",j54);
        cells.put("j55",j55);
        cells.put("j56",j56);
        cells.put("j57",j57);
        cells.put("j58",j58);
        
        //Seventh Row
        cells.put("j60",j60);
        cells.put("j61",j61);
        cells.put("j62",j62);
        cells.put("j63",j63);
        cells.put("j64",j64);
        cells.put("j65",j65);
        cells.put("j66",j66);
        cells.put("j67",j67);
        cells.put("j68",j68);
        
        //Eigth Row
        cells.put("j70",j70);
        cells.put("j71",j71);
        cells.put("j72",j72);
        cells.put("j73",j73);
        cells.put("j74",j74);
        cells.put("j75",j75);
        cells.put("j76",j76);
        cells.put("j77",j77);
        cells.put("j78",j78);
        
        //Ninth Row
        cells.put("j80",j80);
        cells.put("j81",j81);
        cells.put("j82",j82);
        cells.put("j83",j83);
        cells.put("j84",j84);
        cells.put("j85",j85);
        cells.put("j86",j86);
        cells.put("j87",j87);
        cells.put("j88",j88);
    }
    
    public void addKeyListeners(){
        
        /*
        * Objective: Create & Add KeyListener Object to all the text fields in the Sudoku GUI
        * Input: NULL
        * Output: NULL
        */
        
        keyListener = new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
            }

            @Override
            public void keyPressed(KeyEvent e) {
            }

            @Override
            public void keyReleased(KeyEvent e) {
                if(!"123456789".contains(String.valueOf(e.getKeyChar()))){
                    ((JTextField)e.getSource()).setText("");
                }
            }
        };
        
        for(int i = 0;i < max_size;i++){
            for(int j = 0;j < max_size;j++)
                cells.get("j"+i+j).addKeyListener(keyListener);
        }
    }
    
    public void setRandomCells(){
        
        /*
        * Objective: Display approximately 35 numbers per Sudoku with at maximum 5 Numbers per Grid
        * Input: Puzzle Sudoku
        * Output: NULL
        * Approach: Consider each of the 9 grids i the Sudoku. For each Grid select few positions out of 9 possibilities
        *           and display those possiblities based on each Grid
        */
        
        int row,column,nos_per_grid;
        //9 Possible positions in grid starting with 00
        ArrayList<Integer> possible = new ArrayList<>(Arrays.asList(00,01,02,10,11,12,20,21,22));
        Font f = new Font("Tahoma",Font.BOLD,18);
        for(int i = 0;i < 9;i+=3){
            for(int j = 0;j < 9;j+=3){
                //Shuffling the ArrayList for different possibilities each time
                Collections.shuffle(possible);
                //Random Number of cell to be displayed per Grid
                nos_per_grid = (int)(Math.random()*6 + 1);
                for(int temp = 0;temp < nos_per_grid;temp++){
                    //Getting Row and Column Number from the ArrayList Number
                    row = possible.get(temp)/10 + i;
                    column = possible.get(temp)%10 + j;
                    cells.get("j"+row+column).setFont(f);
                    cells.get("j"+row+column).setText("" + generator.puzzle[row][column]);
                    cells.get("j"+row+column).setEditable(false);
                }
            }
        }
    }
    
    public void getResult(){
        
        /**
         * Objective: Take input from all the Cells of JForm and store global Array 'answerSudoku'.
         *            Also validate the input in each Cell
         * Input: NULL
         * Output: NULL
         */
        
        String key;
        String temporary;
        outer:
        for(int i = 0;i < max_size;i++){
            for(int j = 0;j < max_size;j++){
                key = "j" + i + j;
                temporary = cells.get(key).getText();
                if(temporary.length() > 1 || !"123456789".contains(temporary)){
                    cells.get(key).setText("");
                    JOptionPane.showMessageDialog(this, "Please Enter a Valid Number");
                }else if(temporary.length() == 0){ temporary = "0"; }
                if(Integer.parseInt(temporary) != generator.puzzle[i][j]){
                    JOptionPane.showMessageDialog(this, "Incorrect Result");
                    break outer;
                }
            }
        }
    }
    
    private void submitSudokuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitSudokuActionPerformed
        // TODO add your handling code here:
        getResult();
    }//GEN-LAST:event_submitSudokuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Heading;
    private javax.swing.JTextField j00;
    private javax.swing.JTextField j01;
    private javax.swing.JTextField j02;
    private javax.swing.JTextField j03;
    private javax.swing.JTextField j04;
    private javax.swing.JTextField j05;
    private javax.swing.JTextField j06;
    private javax.swing.JTextField j07;
    private javax.swing.JTextField j08;
    private javax.swing.JTextField j10;
    private javax.swing.JTextField j11;
    private javax.swing.JTextField j12;
    private javax.swing.JTextField j13;
    private javax.swing.JTextField j14;
    private javax.swing.JTextField j15;
    private javax.swing.JTextField j16;
    private javax.swing.JTextField j17;
    private javax.swing.JTextField j18;
    private javax.swing.JTextField j20;
    private javax.swing.JTextField j21;
    private javax.swing.JTextField j22;
    private javax.swing.JTextField j23;
    private javax.swing.JTextField j24;
    private javax.swing.JTextField j25;
    private javax.swing.JTextField j26;
    private javax.swing.JTextField j27;
    private javax.swing.JTextField j28;
    private javax.swing.JTextField j30;
    private javax.swing.JTextField j31;
    private javax.swing.JTextField j32;
    private javax.swing.JTextField j33;
    private javax.swing.JTextField j34;
    private javax.swing.JTextField j35;
    private javax.swing.JTextField j36;
    private javax.swing.JTextField j37;
    private javax.swing.JTextField j38;
    private javax.swing.JTextField j40;
    private javax.swing.JTextField j41;
    private javax.swing.JTextField j42;
    private javax.swing.JTextField j43;
    private javax.swing.JTextField j44;
    private javax.swing.JTextField j45;
    private javax.swing.JTextField j46;
    private javax.swing.JTextField j47;
    private javax.swing.JTextField j48;
    private javax.swing.JTextField j50;
    private javax.swing.JTextField j51;
    private javax.swing.JTextField j52;
    private javax.swing.JTextField j53;
    private javax.swing.JTextField j54;
    private javax.swing.JTextField j55;
    private javax.swing.JTextField j56;
    private javax.swing.JTextField j57;
    private javax.swing.JTextField j58;
    private javax.swing.JTextField j60;
    private javax.swing.JTextField j61;
    private javax.swing.JTextField j62;
    private javax.swing.JTextField j63;
    private javax.swing.JTextField j64;
    private javax.swing.JTextField j65;
    private javax.swing.JTextField j66;
    private javax.swing.JTextField j67;
    private javax.swing.JTextField j68;
    private javax.swing.JTextField j70;
    private javax.swing.JTextField j71;
    private javax.swing.JTextField j72;
    private javax.swing.JTextField j73;
    private javax.swing.JTextField j74;
    private javax.swing.JTextField j75;
    private javax.swing.JTextField j76;
    private javax.swing.JTextField j77;
    private javax.swing.JTextField j78;
    private javax.swing.JTextField j80;
    private javax.swing.JTextField j81;
    private javax.swing.JTextField j82;
    private javax.swing.JTextField j83;
    private javax.swing.JTextField j84;
    private javax.swing.JTextField j85;
    private javax.swing.JTextField j86;
    private javax.swing.JTextField j87;
    private javax.swing.JTextField j88;
    private javax.swing.JButton submitSudoku;
    // End of variables declaration//GEN-END:variables

}
